import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Ewani",
      email: "ewani.v2web@gmail.com",
      password: bcrypt.hashSync("Ewani123"),
      isAdmin: true,
    },
    {
      name: "Ewu",
      email: "ewani.sukhadia@gmail.com",
      password: bcrypt.hashSync("Ewu123"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/image1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 10,
      description: "A popular shirt",
    },
    {
      name: "Neck Top",
      slug: "free-top",
      category: "Shirts",
      image: "/images/image2.jpg",
      price: 80,
      brand: "Adidas",
      rating: 3.2,
      numReviews: 10,
      countInStock: 10,
      description: "A popular top",
    },
    {
      name: "Dress",
      slug: "slim-dress",
      category: "Shirts",
      image: "/images/image3.jpg",
      price: 90,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 3,
      countInStock: 10,
      description: "A popular dress",
    },
    {
      name: "Short Frok",
      slug: "free-fro k",
      category: "Pants",
      image: "/images/image4.jpg",
      price: 90,
      brand: "Oliver",
      rating: 2.9,
      numReviews: 13,
      countInStock: 10,
      description: "Smart looking forks",
    },
    {
      name: "Gown Dress",
      slug: "fit-dress",
      category: "Pants",
      image: "/images/image5.jpg",
      price: 95,
      brand: "Zara",
      rating: 3.5,
      numReviews: 7,
      countInStock: 10,
      description: "A popular gown",
    },
    {
      name: "Long Kurti",
      slug: "classic-kurti",
      category: "Pants",
      image: "/images/image6.jpg",
      price: 95,
      brand: "Casely",
      rating: 2.4,
      numReviews: 14,
      countInStock: 10,
      description: "A popular kurti",
    },
    {
      name: "Crop Top",
      slug: "short-top",
      category: "Pants",
      image: "/images/image7.jpg",
      price: 75,
      brand: "Casely",
      rating: 2.4,
      numReviews: 14,
      countInStock: 10,
      description: "A popular crop top",
    },
    {
      name: "Shrug Top",
      slug: "free-shrug",
      category: "Pants",
      image: "/images/image8.jpg",
      price: 90,
      brand: "Casely",
      rating: 2.4,
      numReviews: 14,
      countInStock: 10,
      description: "A popular shrug",
    },
  ],
};

export default data;
